apiVersion: apps/v1
kind: Deployment
metadata:
  name: saral-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saral-backend
  template:
    metadata:
      labels:
        app: saral-backend
    spec:
      containers:
        - name: saral-backend
          image: registry.hub.docker.com/saaral123/backendapi:2.0
          ports:
            - containerPort: 3005
          env:
            - name: PROFILE
              value: dev
            - name: PORT
              value: "3005"
            - name: MONGODB_URL
              value: "mongodb://saral-mongodb:27017/saralv1newdb"
            - name: JWT_SECRET
              value: SARALDATA_NODE
            - name: MONGODB_POOL_SIZE
              value: "5"
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          hostPath:
            path: /usr/local/mongodb/data/db
      restartPolicy: Always
