openapi: 3.0.0
info:
  title: Saral Scanner specification for scanner component
  description: >-
    The schema defines the communication interface between the UI layer and scanner layer.
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 0.7.0
servers:
  - url: /none
paths: {}

components:
  schemas:
    roiConfigs:
      type: array
      items:
        $ref: '#/components/schemas/roiConfig'
        minItems: 1
  
    roiConfig:
      type: object
      description: a scanning area defined on the image. Scanning application will extract the result based upon 'roiId' and update the 'result' key
      required:
        - roiId
        - extractionMethod
        - roi
      properties:
        roiId:
          type: string
          description: unique roi identifier
          format: uuidv4
        extractionMethod:
          type: string
          example: NUMERIC_CLASSIFICATION
          enum:
            - NUMERIC_CLASSIFICATION
            - CELL_OMR
        roi:
          $ref: '#/components/schemas/roi'
        result:
          $ref: '#/components/schemas/scanResult'

    roi:
      type: object
      required:
        - top
        - left
        - bottom
        - right
      properties:
        top:
          type: number
          description: x-coordinate of the ROI on the image
        left:
          type: number
          description: y-coordinate of the ROI on the image
        bottom:
          type: number
          description: x-coordinate of the ROI on the image
        right:
          type: number
          description: y-coordinate of the ROI on the image
          
    scanResult:
      type: object
      description: result of data extraction
      properties:
        prediction:
          type: number
          description: detected data
        confidence:
          type: number
          description: degree of confidence regarding the prediction
    